In [1]:
import numpy as np

In [2]:
a = np.arange(4).reshape((2,2))

In [3]:
a

array([[0, 1],
       [2, 3]])

In [4]:
np.amax(a) 

3

In [5]:
np.amax(a, axis=0)

array([2, 3])

In [6]:
np.amax(a, axis=1)

array([1, 3])

In [7]:
np.amax(a, where=[False, True], initial=-1, axis=0)

array([-1,  3])

In [8]:
b = np.arange(5, dtype=float)

In [9]:
b[2] = np.NaN

In [10]:
np.amax(b)

nan

In [11]:
np.amax(b, where=~np.isnan(b), initial=-1)

4.0

In [12]:
np.nanmax(b)

4.0

In [13]:
np.amax([[-50], [10]], axis=-1, initial=0)

array([ 0, 10])

In [14]:
np.amax([5], initial=6)

6

In [15]:
max([5], default=6)

5